[versions]
apache-bval = { strictly = '3.0.2' }
apacheCommonsCollections = { strictly = '4.5.0' }
apacheCommonsText = { strictly = '1.14.0' }
configTypesafe = { strictly = '1.4.3' }
cucumber = { strictly = '7.23.0' }
dynamoDbLocal = { strictly = '2.0.0' }
glassfish-el = { strictly = '4.0.2' }
hamcrestSpotify = { strictly = '1.3.2' }
httpcore = { strictly = '5.3.6' }
jakarta-el-api = { strictly = '6.0.1' }
jakarta-validation-api = { strictly = '3.1.1' }
jsonassert = { strictly = '1.5.3'}
junit = { strictly = '5.13.3' }
nva-language = { strictly = '1.2.1' }
nvaDoiPartnerData = { strictly = '0.5.8' }
reflections = { strictly = '0.10.2' }
resilience4j = { strictly = '2.3.0' }
swaggerCoreVersion = { strictly = '2.2.34' }
tika = { strictly = '3.2.3' }
vavrVersion = { strictly = '0.10.6' }

[libraries]
nva-language = { group = 'com.github.bibsysdev', name = 'nva-language', version.ref = 'nva-language' }
nva-doi-partner-data = { group = 'com.github.BIBSYSDEV.nva-doi-partner-data', name = 'datacite-transform', version.ref = 'nvaDoiPartnerData' }
jsonassert = { group = 'org.skyscreamer', name = 'jsonassert', version.ref = 'jsonassert' }
jakarta-validation-api = { group = 'jakarta.validation', name = 'jakarta.validation-api', version.ref = 'jakarta-validation-api' }
jakarta-el-api = {group = 'jakarta.el', name = 'jakarta.el-api', version.ref = 'jakarta-el-api' }
glassfish-el = {group = 'org.glassfish', name = 'jakarta.el', version.ref = 'glassfish-el' }
apache-bval = { group= 'org.apache.bval', name= 'bval-jsr', version.ref= 'apache-bval'}
httpcore = { group = 'org.apache.httpcomponents.core5', name = 'httpcore5', version.ref = 'httpcore' }
apache-commons-collections = { group = 'org.apache.commons', name = 'commons-collections4', version.ref = 'apacheCommonsCollections' }
apache-commons-text = { group = 'org.apache.commons', name = 'commons-text', version.ref = 'apacheCommonsText' }
jaxb-runtime = { group = 'org.glassfish.jaxb', name = 'jaxb-runtime', version = '2.3.1' }
xsd2java-xjc = { group = 'com.sun.xml.bind', name = 'jaxb-xjc', version = '4.0.5' }
xsd2java-impl = { group = 'com.sun.xml.bind', name = 'jaxb-impl', version = '4.0.5' }
xsd2java-api = { group = 'javax.xml.bind', name = 'jaxb-api', version = '2.4.0-b180830.0359' }
xsd2java-activation = { group = 'javax.activation', name = 'javax.activation-api', version = '1.2.0' }
xsd2java-jakarta = { group = 'jakarta.xml.bind', name = 'jakarta.xml.bind-api', version = '3.0.1' }
dynamodDbLocal = { group = 'com.amazonaws', name = 'DynamoDBLocal', version.ref = 'dynamoDbLocal' }
typesafe-config = { group = 'com.typesafe', name = 'config', version.ref = 'configTypesafe' }
hamcrest-optional = { group = 'com.spotify', name = 'hamcrest-optional', version.ref = 'hamcrestSpotify' }
hamcrest-json = {  group = 'uk.co.datumedge', name = 'hamcrest-json', version = '0.3' }
junit-vintage-engine = { group = 'org.junit.vintage', name = 'junit-vintage-engine', version.ref = 'junit' }
cucumber-junit = { group = 'io.cucumber', name = 'cucumber-junit', version.ref = 'cucumber' }
tika-core = { group = 'org.apache.tika', name = 'tika-core', version.ref = 'tika' }
tika-langdetect = { group = 'org.apache.tika', name = 'tika-langdetect', version.ref = 'tika' }
tika-langdetect-optimaize = { group = 'org.apache.tika', name = 'tika-langdetect-optimaize', version.ref = 'tika' }
vavr = { group = 'io.vavr', name = 'vavr', version.ref = 'vavrVersion' }
resilience4j-all = { group = 'io.github.resilience4j', name = 'resilience4j-all', version.ref = 'resilience4j' }
swagger-core = { group = 'io.swagger.core.v3', name = 'swagger-core', version.ref = 'swaggerCoreVersion' }
mockito-junit-jupiter = {group= 'org.mockito', name= 'mockito-junit-jupiter', version= '5.3.1'}
reflections = { group = 'org.reflections', name = 'reflections', version.ref = 'reflections' }

[bundles]
validation = ['jakarta-validation-api', 'jakarta-el-api', 'glassfish-el', 'apache-bval']
jaxb = ['xsd2java-api', 'jaxb-runtime', 'xsd2java-jakarta']
xsd2java = ["xsd2java-xjc", "xsd2java-impl", "xsd2java-api", "xsd2java-activation", "xsd2java-jakarta"]